  services:
    db:
      image: postgres:latest
      container_name: bmc_db
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: db
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    pgadmin:
      image: dpage/pgadmin4
      container_name: bmc_pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "8081:80"
      depends_on:
        - db
    
    redis:
      image: redis:latest
      container_name: bmc_redis
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data

  volumes:
    postgres_data:
    redis_data: