// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pg

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	ProfileImageUrl     pgtype.Text
	FullName            pgtype.Text
	CreatingDescription pgtype.Text
	AboutMe             pgtype.Text
	VideoUrl            pgtype.Text
	SocialLinks         []string
	ThemeColor          pgtype.Text
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
